spring:
  application:
    name: banking-app
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  expiration:
    time: ${JWT_EXPIRATION_TIME}